import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ['latin'] })
import { dark } from '@clerk/themes';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
        appearance={
            {
              baseTheme: dark,
            layout: {
              helpPageUrl: "https://clerk.com/support",
              logoImageUrl: "https://clerk.com/logo.png",
              logoPlacement: "inside",
              privacyPageUrl: "https://clerk.com/privacy",
              showOptionalFields: true,
              socialButtonsPlacement: "bottom",
              socialButtonsVariant: "iconButton",
              termsPageUrl: "https://clerk.com/terms",
                }
            }
          }>
            <html lang="en">
                <body className={`${inter.className} bg-dark-1`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
  )
}
